#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_date () {
    sleep 2m
    touch $2
    if [ ! "$(./ftc $1 -date $3)" == $2 ];
    then
        echo "🔴 Test of the file tree failed for date param \"$3\""
        exit 1
    else
        echo "✅ Test of find with name succeeded (date: \"$3\")."
    fi
}

test_find_date "../arbre" "../arbre/different/especially/sit.avi" "2m" 

function test_find_date_several () {
    sleep $4
    touch $2
    if [ ! "$(./ftc $1 -date $3m | wc -l)" == "$(find "$1" "-mmin" -"$3" -type f | wc -l)" ];
    then
        echo "🔴 Test of the file tree failed for date param \"$3\""
        exit 1
    else
        echo "✅ Test of find with name succeeded (date: \"$3\")."
    fi
}

test_find_date_several "../arbre" "../arbre/improve.mp3" "4" "1m"
test_find_date_several "../arbre" "../arbre/say/official/election/type.mov" "4" "0m"